use supplychainanalytics;
-- =====================================================
-- Create Clean Supply Chain Table
-- =====================================================
-- This table stores the cleaned transactional data after
-- applying data type conversion, text standardization,
-- trimming, and null handling.
-- =====================================================
create table clean_supply_chain (
	type varchar(100),
    days_for_shipping int,
    days_for_shipment int,
    benefit_per_order decimal(10,2),
    sales_per_customer decimal(10,2),
    delivery_status varchar(100),
    late_delivery_risk int,
    category_id int,
    category_name varchar(100),
    customer_city varchar(100),
    customer_country varchar(100),
    customer_fname varchar(100),
    customer_id int,
    customer_lname varchar(100),
    customer_segment varchar(100),
    customer_state varchar(100),
    customer_zipcode varchar(20),
    department_id int,
    department_name varchar(100),
    latitude double,
    longitude double,
    market varchar(100),
    order_city varchar(100),
    order_country varchar(100),
    order_customer_id int,
    order_date datetime,
    order_id int,
    order_item_cardprod_id int,
    order_item_discount decimal(10,2),
    order_item_discount_rate double,
    order_item_id int primary key,
    order_item_product_price decimal(10,2),
    order_item_profit_ratio double,
    order_item_quantity int,
    sales decimal(10,2),
    order_item_total decimal(10,2),
    order_profit_per_order decimal(10,2),
    order_region varchar(100),
    order_state varchar(100),
    order_status varchar(100),
    order_zipcode varchar(20),
    product_card_id int,
    product_category_id int,
    product_description text,
    product_name varchar(100),
    product_price decimal(10,2),
    product_status int,
    shipping_date datetime,
    shipping_mode varchar(100)
    );