use supplychainanalytics;
-- =====================================================
-- Load Clean Supply Chain Table
-- =====================================================
-- Data transformations performed:
-- • Trim leading/trailing spaces
-- • Convert country names to uppercase
-- • Convert date strings to DATETIME
-- • Replace blank zipcodes with NULL
-- • Standardize text columns
-- =====================================================
insert into clean_supply_chain (
	type,
    days_for_shipping,
    days_for_shipment,
    benefit_per_order,
    sales_per_customer,
    delivery_status,
    late_delivery_risk,
    category_id,
    category_name,
    customer_city,
    customer_country,
    customer_fname,
    customer_id,
    customer_lname,
    customer_segment,
    customer_state,
    customer_zipcode,
    department_id,
    department_name,
    latitude,
    longitude,
    market,
    order_city,
    order_country,
    order_customer_id,
    order_date,
    order_id,
    order_item_cardprod_id,
    order_item_discount,
    order_item_discount_rate,
    order_item_id,
    order_item_product_price,
    order_item_profit_ratio,
    order_item_quantity,
    sales,
    order_item_total,
    order_profit_per_order,
    order_region,
    order_state,
    order_status,
    order_zipcode,
    product_card_id,
    product_category_id,
    product_description,
    product_name,
    product_price,
    product_status,
    shipping_date,
    shipping_mode
    )
    select
    `Type`,
    `Days for shipping (real)`,
    `Days for shipment (scheduled)`,
    `Benefit per order`,
    `Sales per customer`,
    `Delivery Status`,
    `Late_delivery_risk`,
    `Category Id`,
    trim(`Category Name`),
    trim(`Customer City`),
    upper(trim(`Customer Country`)),
    trim(`Customer Fname`),
    `Customer Id`,
    trim(`Customer Lname`),
    trim(`Customer Segment`),
    trim(`Customer State`),
    nullif(trim(`Customer Zipcode`), ''),
    `Department Id`,
    trim(`Department Name`),
    `Latitude`,
    `Longitude`,
    `Market`,
    trim(`Order City`),
    upper(trim(`Order Country`)),
    `Order Customer Id`,
    str_to_date(`order date (DateOrders)`,'%m/%d/%Y %H:%i'),
    `Order Id`,
    `Order Item Cardprod Id`,
    `Order Item Discount`,
    `Order Item Discount Rate`,
    `Order Item Id`,
    `Order Item Product Price`,
    `Order Item Profit Ratio`,
    `Order Item Quantity`,
    `Sales`,
    `Order Item Total`,
    `Order Profit Per Order`,
    `Order Region`,
    trim(`Order State`),
    `Order Status`,
    nullif(trim(`Order Zipcode`),''),
    `Product Card Id`,
    `Product Category Id`,
    `Product Description`,
    trim(`Product Name`),
    `Product Price`,
    `Product Status`,
    str_to_date(`shipping date (DateOrders)`,'%m/%d/%Y %H:%i'),
    trim(`Shipping Mode`)
    From stg_supply_chain;
    
-- Validate row count
SELECT COUNT(*)
FROM clean_supply_chain;